Repository DodamDuck/DodamDuck, pull requests merged in 2023-12, with the labels that each got.

#160 [FE] feat: 채팅 걸기(채팅방 생성) API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/BoardPost.js
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/ChattingDetail.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
Labels: ✨ 기능 구현

#168 [FE] feat: 1:1 채팅 내역 가져오기 API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/ChattingDetail.js
Labels: 디자인 🎨, ✨ 기능 구현

#170 [FE] feat: 1:1 채팅 메세지 보내기 API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/ChattingDetail.js
Labels: ✨ 기능 구현

#172 [FE] feat: 장난감 도서관 사진 적용
  dodamduck_fe/src/Library.js
Labels: ✨ 기능 구현

#174 [AOS] feat: 거래/나눔 검색 기능 구현
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/database/DodamDuckDatabase.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/database/SearchHistory.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/database/SearchHistoryDao.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/di/DatabaseModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Search.kt
Labels: 디자인 🎨, ✨ 기능 구현

#176 [FE] design: 채팅 UI 수정 및 폰트 적용
  dodamduck_fe/src/App.css
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/ChattingDetail.js
  dodamduck_fe/src/Main4.js
  dodamduck_fe/src/assets/fonts/Gugi-Regular.ttf
  dodamduck_fe/src/assets/fonts/fonts.css
Labels: 디자인 🎨

#178 [AOS] release: 테스트 앱 배포
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/google-services.json
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/SearchDTO.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/DummyItemFactory.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Chat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Search.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/utils/Utils.kt
  dodamduck_aos/app/src/main/res/drawable/img_user_profile.png
  dodamduck_aos/build.gradle.kts
Labels: 🛠 설정, 🔥 배포

#181 [FE] feat: 내 상점에 교환/나눔 API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/MyShop.js
  dodamduck_fe/src/SharingDetail.js
Labels: 디자인 🎨, ✨ 기능 구현

#184 [AOS] test: UI 테스트 설정 및 온보딩 화면 네비게이션 테스트 코드 작성
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/androidTest/java/org/chosun/dodamduck/ScreenNavigationTest.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
Labels: ✨ 기능 구현, 🛠 설정
