Repository DodamDuck/DodamDuck, pull requests merged in 2023-10, with the labels that each got.

#8 [FE] chore: 프로젝트 다시 세팅
  dodamduck_fe/.gitignore
  dodamduck_fe/README.md
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/public/index.html
  dodamduck_fe/public/manifest.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/App.test.js
  dodamduck_fe/src/index.css
  dodamduck_fe/src/index.js
  dodamduck_fe/src/reportWebVitals.js
  dodamduck_fe/src/setupTests.js
Labels: 🛠 설정

#10 [FE] feat: navbar 생성
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/img/도담덕로고.png
Labels: ✨ 기능 구현

#11 [FE} chore: resolve merge conflicts
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/assets/fonts/210 옴니고딕OTF 025.otf
  dodamduck_fe/src/assets/fonts/210 옴니고딕OTF 035.otf
  dodamduck_fe/src/assets/fonts/210 옴니고딕OTF 045.otf
  dodamduck_fe/src/assets/fonts/fonts.css
Labels: 🛠 설정

#13 [AOS] feat: 화면 추가 및 네비게이션
  .github/ISSUE_TEMPLATE/이슈-템플릿-.md
  app/build.gradle.kts
  app/src/main/java/org/chosun/dodamduck/MainActivity.kt
  app/src/main/java/org/chosun/dodamduck/ui/Board.kt
  app/src/main/java/org/chosun/dodamduck/ui/Chat.kt
  app/src/main/java/org/chosun/dodamduck/ui/Home.kt
  app/src/main/java/org/chosun/dodamduck/ui/Library.kt
  app/src/main/java/org/chosun/dodamduck/ui/Login.kt
  app/src/main/java/org/chosun/dodamduck/ui/Register.kt
  app/src/main/java/org/chosun/dodamduck/ui/User.kt
  app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  app/src/main/res/drawable/ic_board_48.png
  app/src/main/res/drawable/ic_chat_48.png
  app/src/main/res/drawable/ic_home_48.png
  app/src/main/res/drawable/ic_toy_48.png
  app/src/main/res/drawable/ic_user_48.png
  app/src/main/res/values/strings.xml
Labels: 디자인 🎨, ✨ 기능 구현

#15 [FE] fix: 충돌 해결
  dodamduck_fe/src/App.css
Labels: 버그 수정 🐞

#17 [FE] design: 폰트 적용
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
Labels: 디자인 🎨

#20 [FE] design: 메인 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Main1.js
  dodamduck_fe/src/Main2.js
  dodamduck_fe/src/Main3.js
  dodamduck_fe/src/img/도담덕캐릭터.png
  dodamduck_fe/src/img/도담덕캐릭텨(누끼).png
Labels: 디자인 🎨

#22 [AOS] chore: 폴더링
  app/src/main/java/org/chosun/dodamduck/MainActivity.kt
  app/src/main/res/values/strings.xml
  dodamduck_aos/.gitignore
  dodamduck_aos/README.md
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/proguard-rules.pro
  dodamduck_aos/app/src/androidTest/java/org/chosun/dodamduck/ExampleInstrumentedTest.kt
  dodamduck_aos/app/src/main/AndroidManifest.xml
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/MainActivity.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Board.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Chat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Home.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Library.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Login.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Register.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/User.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Button.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Image.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/RoundBox.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Color.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Theme.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Type.kt
  dodamduck_aos/app/src/main/res/drawable/ic_board_48.png
  dodamduck_aos/app/src/main/res/drawable/ic_chat_48.png
  dodamduck_aos/app/src/main/res/drawable/ic_duck.png
  dodamduck_aos/app/src/main/res/drawable/ic_home_48.png
  dodamduck_aos/app/src/main/res/drawable/ic_launcher_background.xml
  dodamduck_aos/app/src/main/res/drawable/ic_launcher_foreground.xml
  dodamduck_aos/app/src/main/res/drawable/ic_toy_48.png
  dodamduck_aos/app/src/main/res/drawable/ic_user_48.png
  dodamduck_aos/app/src/main/res/font/krona.ttf
  dodamduck_aos/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  dodamduck_aos/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  dodamduck_aos/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  dodamduck_aos/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  dodamduck_aos/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  dodamduck_aos/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  dodamduck_aos/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  dodamduck_aos/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  dodamduck_aos/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  dodamduck_aos/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  dodamduck_aos/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  dodamduck_aos/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  dodamduck_aos/app/src/main/res/values/colors.xml
  dodamduck_aos/app/src/main/res/values/strings.xml
  dodamduck_aos/app/src/main/res/values/themes.xml
  dodamduck_aos/app/src/main/res/xml/backup_rules.xml
  dodamduck_aos/app/src/main/res/xml/data_extraction_rules.xml
  dodamduck_aos/app/src/test/java/org/chosun/dodamduck/ExampleUnitTest.kt
  dodamduck_aos/build.gradle.kts
  dodamduck_aos/gradle.properties
  dodamduck_aos/gradle/wrapper/gradle-wrapper.jar
  dodamduck_aos/gradle/wrapper/gradle-wrapper.properties
  dodamduck_aos/gradlew
  dodamduck_aos/gradlew.bat
  dodamduck_aos/local.properties
  dodamduck_aos/settings.gradle.kts
Labels: 🛠 설정

#25 [FE] design: 이미지 삽입
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Main1.js
  dodamduck_fe/src/Main2.js
  dodamduck_fe/src/Main3.js
  dodamduck_fe/src/Main4.js
  dodamduck_fe/src/img/안드로이드_도서관.png
  dodamduck_fe/src/img/안드로이드_로그인.png
  dodamduck_fe/src/img/안드로이드_메인.png
  dodamduck_fe/src/img/안드로이드_손.png
  dodamduck_fe/src/img/안드로이드_홈.png
Labels: 디자인 🎨

#26 [FE] design: 네브바 색깔 변경
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
Labels: 디자인 🎨

#27 [FE] feat: 스크롤 이벤트 테스트
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Main2.js
  dodamduck_fe/src/Main3.js
Labels: ✨ 기능 구현

#29 [FE] design: 로그인 화면 구현
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/LoginPage.js
  dodamduck_fe/src/Main3.js
  dodamduck_fe/src/index.js
Labels: 디자인 🎨, ✨ 기능 구현

#31 [FE] design: 회원가입 화면 구현
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/LoginPage.js
  dodamduck_fe/src/SignupPage.js
Labels: 디자인 🎨, ✨ 기능 구현

#32 [AOS] feat: 회원 가입 버튼 클릭 시 화면 전환
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/DodamDuckApp.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/MainActivity.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Onboarding.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Register.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/EditText.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_fe/.gitignore
  dodamduck_fe/README.md
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/public/index.html
  dodamduck_fe/public/manifest.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/App.test.js
  dodamduck_fe/src/index.css
  dodamduck_fe/src/index.js
  dodamduck_fe/src/reportWebVitals.js
  dodamduck_fe/src/setupTests.js
Labels: 디자인 🎨, ✨ 기능 구현

#36 [FE] feat: Navbar 구현
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Library.js
Labels: 디자인 🎨

#37 [FE] feat: 장난감 도서관 API 호출
  dodamduck_fe/.env
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/Library.js
Labels: ✨ 기능 구현

#38 [FE] design: 장난감 도서관 화면 UI 구현
  dodamduck_fe/public/index.html
  dodamduck_fe/src/App.css
  dodamduck_fe/src/Library.js
Labels: 디자인 🎨

#43 [FE] design: 연결 및 네브바 구현
  dodamduck_fe/src/App.js
  dodamduck_fe/src/SharingBoard.js
Labels: 디자인 🎨

#44 [FE] feat: 글 등록 버튼 생성 및 useNavigate로 연결
  dodamduck_fe/package-lock.json
  dodamduck_fe/package.json
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingPost.js
Labels: 디자인 🎨, ✨ 기능 구현

#47 [FE] design: 교환/나눔 글 등록 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingPost.js
Labels: 디자인 🎨

#48 [AOS] design: 나눔, 교환 화면 UI
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Home.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/ToyItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/res/drawable/ic_comment_26.png
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#50 [FE] feat: 이미지 등록 기능
  dodamduck_fe/src/SharingPost.js
Labels: ✨ 기능 구현

#51 [FE] feat: 글 등록 기능
  dodamduck_fe/src/App.js
  dodamduck_fe/src/PostContext.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingPost.js
Labels: ✨ 기능 구현

#52 [AOS] chore: hilt, retrofit2 설정
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/main/AndroidManifest.xml
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/DodamDuckApplication.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/MainActivity.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/ToyInfo.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/OpenApiResponse.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/RetrofitClient.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/ToyLibraryApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/ToyLibraryRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/ToyLibraryViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Library.kt
  dodamduck_aos/build.gradle.kts
Labels: 🛠 설정

#55 [AOS] design: 홈 화면 버튼 추가
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Home.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨
