Repository DodamDuck/DodamDuck, pull requests merged in 2023-11, with the labels that each got.

#56 [FE] design: 교환/나눔 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingPost.js
Labels: 디자인 🎨

#59 [FE] design: 연결 및 네브바 구현
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Board.js
Labels: 디자인 🎨

#60 [FE] design: 게시판 글 등록 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/BoardPost.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingPost.js
Labels: 디자인 🎨

#61 [FE] chore: 변경사항 커밋 및 연결
  dodamduck_fe/장난감사진.avif
Labels: 🛠 설정

#62 [FE] design: 게시판 전체적인 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/Board.js
Labels: 디자인 🎨

#64 [FE] design: 글 등록 화면 디자인 변경
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingPost.js
Labels: 디자인 🎨

#65 [FE] feat: 게시판 글 등록 기능
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/BoardPost.js
Labels: ✨ 기능 구현

#67 [AOS] design: 게시글 작성화면
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Library.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Onboarding.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/AuthBody.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Box.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Button.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Surface.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PhotoLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ToyLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Color.kt
  dodamduck_aos/app/src/main/res/drawable/ic_camera_20.xml
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#71 [AOS] design: 게시글 화면
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Board.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Login.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Trade.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/TradeWrite.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Button.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PostLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/TagLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Color.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#72 [FE] design: 내 상점 UI 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/MyShop.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/sharingData.js
Labels: 디자인 🎨

#76 [AOS] design: 게시글 작성 화면
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostWrite.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/TradeWrite.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Color.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#77 [FE] design: 채팅 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Chatting.js
Labels: 디자인 🎨

#79 [AOS] desgin: 게시물 상세 화면 구현
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/DummyItemFactory.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/state/PostDetailUserInfoState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Image.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PostLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/res/drawable/img_user_profile.png
  dodamduck_aos/app/src/main/res/drawable/img_user_profile_2.jpeg
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#81 [AOS] design: 채팅 리스트 화면 UI
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/ChatList.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
Labels: 디자인 🎨

#83 [AOS] design: 채팅 리스트 화면
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/ChatList.kt
Labels: 디자인 🎨

#84 [FE] design: 채팅 상세 화면 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/ChattingDetail.js
Labels: 디자인 🎨

#86 [AOS] design: 채팅화면 UI 구현
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/ChatInfo.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Chat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/ChatList.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Button.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ChatLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/theme/Color.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#88 [AOS] feat: 유저 화면 UI 구현
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/User.kt
Labels: 디자인 🎨

#90 [FE] design: 교환&나눔 상세 페이지 UI 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/SharingDetail.js
Labels: 디자인 🎨

#91 [FE] design: 게시판 UI 디자인
  dodamduck_fe/src/App.js
  dodamduck_fe/src/BoardDetail.js
Labels: 디자인 🎨

#94 [FE] feat: 교환/나눔 전체 조회 연동
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/SharingBoard.js
Labels: ✨ 기능 구현

#95 [FE] feat: 도담덕 게시판 전체 조회 연동
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/SharingBoard.js
Labels: ✨ 기능 구현

#99 [AOS] feat: 거래/나눔 API 연동
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/main/AndroidManifest.xml
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/Trade.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/RetrofitClient.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Trade.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/utils/DateUtil.kt
  dodamduck_aos/app/src/main/res/xml/network_security_config.xml
Labels: 디자인 🎨, ✨ 기능 구현

#100 [FE] feat: API연동 - 교환/나눔 상세 조회
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
Labels: ✨ 기능 구현

#101 [FE] feat: API연동 - 게시글 상세 조회
  dodamduck_fe/src/App.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/SharingDetail.js
Labels: ✨ 기능 구현

#105 [FE] design: 교환&나눔 상세 페이지 댓글 UI 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingDetail.js
Labels: 디자인 🎨

#107 [FE] design: 교환&나눔 상세 페이지 댓글 UI 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/BoardDetail.js
Labels: 디자인 🎨

#109 [AOS] feat: 채팅 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/ChatInfo.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/ChatApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/ChatRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/ChatViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Chat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ChatLazy.kt
Labels: 디자인 🎨, ✨ 기능 구현

#112 [FE] feat: 교환/나눔 글 작성 API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
Labels: 디자인 🎨, ✨ 기능 구현

#113 [AOS] feat: 거래 / 나눔 상세보기 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/DodamDuckApp.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/TradeDetailResponse.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Trade.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
Labels: ✏️ 이름 수정, 디자인 🎨, ✨ 기능 구현

#117 [AOS] feat: 로그인 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/data/DodamDuckData.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/LoginDTO.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/AuthApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/AuthRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Login.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/AuthBody.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Image.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/res/drawable/ic_invisible_48.png
  dodamduck_aos/app/src/main/res/drawable/ic_visible.png
  dodamduck_aos/app/src/main/res/drawable/ic_visible_48.png
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨, ✨ 기능 구현

#119 [AOS] feat: 회원가입 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/AuthApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/AuthRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Register.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/AuthBody.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨, ✨ 기능 구현

#122 [AOS] feat: 게시글 조회 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/PostDTO.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PostLazy.kt
Labels: 디자인 🎨, ✨ 기능 구현

#123 [FE] feat: 회원가입 API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/SignupPage.js
Labels: 디자인 🎨, ✨ 기능 구현

#127 [FE] feat: 사용자 아이디 중복 조회 API 연동
  dodamduck_fe/src/SignupPage.js
Labels: ✨ 기능 구현

#129 [AOS] feat: 게시글 상세 보기 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/PostCommentDTO.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/PostDTO.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/PostDetailDTO.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/PostDetailResponse.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/dto/TradeDetailResponse.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Trade.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PostLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
Labels: 디자인 🎨, ✨ 기능 구현

#131 [AOS] feat: 댓글 작성 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
Labels: 디자인 🎨, ✨ 기능 구현

#132 [AOS] feat: 게시글 방문시 조회수 증가시키는 API 연동
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/Post.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PostLazy.kt
Labels: 디자인 🎨

#134 [FE] feat: 로그인 API 연동
  dodamduck_fe/src/App.js
  dodamduck_fe/src/AuthContext.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/BoardPost.js
  dodamduck_fe/src/LoginPage.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SignupPage.js
  dodamduck_fe/src/index.js
Labels: ✨ 기능 구현

#135 [FE] design: 게시글 상세페이지 프로필 기본이미지 추가
  dodamduck_fe/src/BoardDetail.js
Labels: 디자인 🎨

#139 [FE] design: 로그인 API연동 후 UI 수정
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/AuthContext.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/ChattingDetail.js
  dodamduck_fe/src/LoginPage.js
  dodamduck_fe/src/MyShop.js
  dodamduck_fe/src/SharingDetail.js
Labels: 디자인 🎨, ✨ 기능 구현

#141 [AOS] design: 장난감 도서관 사진 적용
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/SearchBar.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ToyLazy.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨

#145 [FE] feat: 교환/나눔 조회수 증가 API 연동
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/BoardPost.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
Labels: ✨ 기능 구현

#146 [FE] feat: 도담덕 게시판 게시글 조회수 증가 API 연동
  dodamduck_fe/src/App.css
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/Library.js
  dodamduck_fe/src/SharingBoard.js
Labels: ✨ 기능 구현

#143 [AOS] feat: 게시글 삭제 기능 및 ViewModel, Screen 분리
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/data/DodamDuckData.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/TradeApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/DummyItemFactory.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/TradeWrite.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/BottomSheet.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Text.kt
Labels: 디자인 🎨, ✨ 기능 구현

#149 [AOS] feat: 장난감 도서관 API 코드 수정 및 사용자 화면 UI 상태 반영
  dodamduck_aos/.gitignore
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/ToyLibraryApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/ToyLibraryRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/User.kt
  dodamduck_aos/gradle.properties
Labels: 디자인 🎨, ✨ 기능 구현

#151 [FE] feat: 교환&나눔 댓글 작성 API 연동
  dodamduck_fe/public/index.html
  dodamduck_fe/src/App.css
  dodamduck_fe/src/App.js
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
Labels: ✨ 기능 구현

#153 [FE] feat: 도담덕 게시판 댓글 작성 API 연동
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/SharingDetail.js
Labels: ✨ 기능 구현

#155 [AOS] feat: 게시글 삭제, 게시글 업로드 API 연동 및 UI 수정
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/network/PostApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/model/viewmodel/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/PostWrite.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/TradeWrite.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/InputText.kt
  dodamduck_aos/app/src/main/res/values/strings.xml
Labels: 디자인 🎨, ✨ 기능 구현
