Repository DodamDuck/DodamDuck, pull requests merged in 2024-03, with the labels that each got.

#186 [FE] comment: 불필요한 주석 삭제
  dodamduck_fe/src/App.js
  dodamduck_fe/src/AuthContext.js
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/Library.js
  dodamduck_fe/src/Main4.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
Labels: 🗨️코멘트

#188 [FE] comment: 불필요한 주석 삭제
  README.md
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/BoardPost.js
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/ChattingDetail.js
  dodamduck_fe/src/LoginPage.js
  dodamduck_fe/src/Main1.js
  dodamduck_fe/src/Main2.js
  dodamduck_fe/src/Main3.js
  dodamduck_fe/src/MyShop.js
  dodamduck_fe/src/SharingDetail.js
  dodamduck_fe/src/SharingPost.js
  dodamduck_fe/src/SignupPage.js
Labels: 🗨️코멘트

#190 [FE] remove: 불필요한 파일 정리
  dodamduck_fe/src/ChatContext.js
  dodamduck_fe/src/ChattingDetail.js
  dodamduck_fe/src/sharingData.js
  dodamduck_fe/src/useScrollSnap.js
Labels: 🎸 기타

#192 [AOS] refactor: 패키지 구조화
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/LoginScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/OnboardingScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/RegisterScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/base/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatListScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/library/LibraryScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/library/ToyLibraryViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostDetailScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/search/SearchScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
Labels: 📁 문서화

#199 [AOS] refactor: Chat, ChatList MVI 적용
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/di/DataModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/ChatRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/ChatRepositoryImpl.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/source/remote/ChatRemoteSource.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/repository/ChatRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/auth/RequestLogin.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/chat/GetChatList.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/chat/GetChats.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/chat/SendChat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/ChatApiService.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatEvent.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatListScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatSideEffect.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatViewModel.kt
Labels: ✨ 기능 구현

#201 [AOS] refactor: Post, Trade, Detail MVI 적용
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/di/ServiceModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/PostRepositoryImpl.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/TradeRepositoryImpl.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/source/local/PostLocalSource.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/source/remote/PostRemoteSource.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/source/remote/TradeRemoteSource.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/repository/PostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/repository/TradeRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/CreateChat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/DeletePost.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/GetPostCategories.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/GetPostDetail.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/GetPostList.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/SearchPost.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/UploadComment.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/UploadPost.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/UploadViewCount.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/base/BasePostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/PostDetailScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/BasePostDetailViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/PostDetailEvent.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/PostDetailReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/PostDetailSideEffect.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/PostDetailState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/post/PostDetailViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/trade/TradeDetailViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostEvent.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostSideEffect.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/write/PostWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/search/SearchScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeEvent.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeSideEffect.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/write/TradeWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
Labels: ✨ 기능 구현

#203 [AOS] refactor: UseCase 추상화
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/dto/auth/AuthDto.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/dto/post/PostDto.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/auth/RequestLogin.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/auth/RequestRegister.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/base/BaseResultUseCase.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/CreateChat.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/BasePostDetailViewModel.kt
Labels: ✨ 기능 구현

#204 [FE] design: 사용자 id일치해야 수정 및 삭제 가능하도록 디자인 수정
  dodamduck_fe/src/SharingDetail.js
Labels: 디자인 🎨

#205 [FE] feat: 내 상점에서 내가 올린 게시물 들어갈 수 있도록 navigation
  README.md
  dodamduck_fe/src/MyShop.js
Labels: ✨ 기능 구현

#207 [FE] design: 교환/나눔 검색 화면 UI 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingBoard.js
Labels: 디자인 🎨

#210 [FE] comment: 필요한 주석 삭제
  dodamduck_fe/src/App.css
  f
Labels: 🗨️ 코멘트

#212 [FE] feat: 회원 정보 없이 카드 클릭 시 로그인페이지로 리다이렉션
  README.md
  dodamduck_fe/README.md
  dodamduck_fe/src/BoardDetail.js
  dodamduck_fe/src/MyShop.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
Labels: ✨ 기능 구현

#214 [FE] feat: 내 상점 및 채팅 탭 클릭시 로그인 페이지로 리다이렉션
  dodamduck_fe/src/Chatting.js
  dodamduck_fe/src/MyShop.js
  dodamduck_fe/src/SharingBoard.js
Labels: ✨ 기능 구현

#215 [FE] feat: 회원 정보 없을 시 댓글 창 및 채팅 버튼 비활성화
  dodamduck_fe/src/App.css
  dodamduck_fe/src/BoardDetail.js
Labels: 디자인 🎨, ✨ 기능 구현

#217 [FE] feat: 회원정보 없을 시 글 올리기 버튼 비활성화
  dodamduck_fe/src/Board.js
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
Labels: ✨ 기능 구현

#219 [AOS] hotfix: 리팩토링 중 발생한 오류 수정
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/di/DataModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/di/ServiceModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/PostRepositoryImpl.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/TradeRepositoryImpl.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/di/RepositoryModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/repository/BasePostRepository.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/auth/RequestRegister.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/post/UploadPost.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/LoginScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/RegisterScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/BasePostDetailViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/write/PostWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/search/SearchScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeSideEffect.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/write/TradeWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/util/ImageExt.kt
  dodamduck_aos/app/src/main/res/drawable/img_no.png
Labels: 버그 수정 🐞

#221 [FE] feat: 인기 검색어 조회 API 연동
  dodamduck_fe/src/SharingBoard.js
  dodamduck_fe/src/SharingDetail.js
Labels: ✨ 기능 구현

#224 [FE] feat: 도담덕 게시판 게시글 삭제 기능 API 연동
  dodamduck_fe/src/BoardDetail.js
Labels: ✨ 기능 구현

#225 [FE] design: 인기 검색어 조회 UI 디자인
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingBoard.js
Labels: 디자인 🎨

#230 [AOS] feat: 비동기 결과 처리 리팩토링
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/SafeApiResult.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthEvent.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/LoginScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/RegisterScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/BasePostDetailViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/library/ToyLibraryEvent.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/library/ToyLibraryReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/library/ToyLibraryViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeViewModel.kt
Labels: ✨ 기능 구현

#231 [FE] design: 교환/나눔 게시판 상세페이지 디자인 변경
  dodamduck_fe/src/App.css
  dodamduck_fe/src/SharingDetail.js
Labels: 디자인 🎨

#233 [AOS] feat: JWT 기능 추가
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/dto/auth/LoginDto.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/data/repository/AuthRepositoryImpl.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/AuthAuthenticator.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/AuthInterceptor.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/AuthTokenRefresher.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/TokenManager.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/TokenRefresher.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/di/AppModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/response/JwtResponse.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/service/AuthApiService.kt
Labels: ✨ 기능 구현

#237 [AOS] design: AccessToken 여부에 따른 앱 시작점 변경
  dodamduck_aos/app/build.gradle.kts
  dodamduck_aos/app/src/androidTest/java/org/chosun/dodamduck/ScreenNavigationTest.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/DodamDuckApp.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/MainActivity.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/AuthInterceptor.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/di/NetworkModule.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/common/LoadingLottieScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/res/raw/toy_lottie.json
Labels: 버그 수정 🐞, 디자인 🎨, ✨ 기능 구현

#239 [AOS] fix: 이미지 선택하지 않고 글 작성시 앱 꺼지는 문제 해결
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/write/PostWriteScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/write/TradeWriteScreen.kt
Labels: 버그 수정 🐞

#243 [AOS] design, fix: 디자인 수정 및 버그 수정
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/DodamDuckApp.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/AuthAuthenticator.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/network/auth/AuthInterceptor.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthSideEffect.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/AuthViewModel.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/PostDetailScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/PostDetailReducer.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/base/PostDetailState.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/modifier/Modifier.kt
Labels: 버그 수정 🐞, 디자인 🎨

#244 [AOS] refactor: Navigation 리팩토링 및 댓글 아이콘 변경
  dodamduck_aos/app/src/androidTest/java/org/chosun/dodamduck/ScreenNavigationTest.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/DodamDuckApp.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/LoginScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/OnboardingScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/auth/RegisterScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/chat/ChatListScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/common/LoadingLottieScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/detail/PostDetailScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/search/SearchScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/trade/TradeScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/Image.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/PostLazy.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/DodamDuckNavigation.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/navigation/Screen.kt
  dodamduck_aos/app/src/main/res/drawable/vc_comment.xml
Labels: 디자인 🎨, ✨ 기능 구현

#246 [AOS] feat: 회원가입 아이디, 비밀번호 유효성 검사 구현
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/domain/usecase/remote/auth/RequestRegister.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/library/LibraryScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/post/PostScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/presentation/search/SearchScreen.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/ui/component/lazy_components/ExchangeItem.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/utils/AuthExt.kt
  dodamduck_aos/app/src/main/java/org/chosun/dodamduck/utils/ModifierExt.kt
  dodamduck_aos/app/src/test/java/org/chosun/dodamduck/ExampleUnitTest.kt
  dodamduck_aos/app/src/test/java/org/chosun/dodamduck/auth/IdValidatorTest.kt
  dodamduck_aos/app/src/test/java/org/chosun/dodamduck/auth/PasswordValidatorTest.kt
Labels: ✨ 기능 구현
